version: "1.0"

services:
  oauth-service:
    build: .
    container_name: oauth-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: go run ./api/main.go
