// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: oauth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OAuthervice_GetOauth_FullMethodName = "/OAuthervice/GetOauth"
)

// OAutherviceClient is the client API for OAuthervice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OAutherviceClient interface {
	GetOauth(ctx context.Context, in *GetOauthReq, opts ...grpc.CallOption) (*GetOAuthResponse, error)
}

type oAutherviceClient struct {
	cc grpc.ClientConnInterface
}

func NewOAutherviceClient(cc grpc.ClientConnInterface) OAutherviceClient {
	return &oAutherviceClient{cc}
}

func (c *oAutherviceClient) GetOauth(ctx context.Context, in *GetOauthReq, opts ...grpc.CallOption) (*GetOAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOAuthResponse)
	err := c.cc.Invoke(ctx, OAuthervice_GetOauth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAutherviceServer is the server API for OAuthervice service.
// All implementations must embed UnimplementedOAutherviceServer
// for forward compatibility.
type OAutherviceServer interface {
	GetOauth(context.Context, *GetOauthReq) (*GetOAuthResponse, error)
	mustEmbedUnimplementedOAutherviceServer()
}

// UnimplementedOAutherviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOAutherviceServer struct{}

func (UnimplementedOAutherviceServer) GetOauth(context.Context, *GetOauthReq) (*GetOAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOauth not implemented")
}
func (UnimplementedOAutherviceServer) mustEmbedUnimplementedOAutherviceServer() {}
func (UnimplementedOAutherviceServer) testEmbeddedByValue()                     {}

// UnsafeOAutherviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OAutherviceServer will
// result in compilation errors.
type UnsafeOAutherviceServer interface {
	mustEmbedUnimplementedOAutherviceServer()
}

func RegisterOAutherviceServer(s grpc.ServiceRegistrar, srv OAutherviceServer) {
	// If the following call pancis, it indicates UnimplementedOAutherviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OAuthervice_ServiceDesc, srv)
}

func _OAuthervice_GetOauth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOauthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAutherviceServer).GetOauth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthervice_GetOauth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAutherviceServer).GetOauth(ctx, req.(*GetOauthReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OAuthervice_ServiceDesc is the grpc.ServiceDesc for OAuthervice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OAuthervice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OAuthervice",
	HandlerType: (*OAutherviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOauth",
			Handler:    _OAuthervice_GetOauth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oauth.proto",
}
